version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    ports:
      - "8081:8081" # Expose backend API

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BiL@18
      MYSQL_DATABASE: barta-news
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
     - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db_data: